---

- name: Uninstall
  hosts: all
  tasks:

    - name: remove apache2 package
      apk:
        name: apache2
        state: absent

    - name: remove curl
      apk:
        name: curl
        state: absent

