    - name: install apache and curl package
      package:
        name: 
          - "{{apache_package}}"
          - "{{curl_package}}"
          - openrc
        state: latest
      when: ansible_distribution == "Alpine"
      notify: start_apache2

    - name: generate sshd_config file from template
      template:
        src: "{{ ssh_template_file}}"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart_sshd