    - name: install apache and curl package
      package:
        name: 
          - "{{apache_package}}"
          - "{{curl_package}}"
          - openrc
        state: latest
      when: ansible_distribution == "Alpine"

    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Alpine"
