- name: install curl package
  package:
    name: 
      - "{{curl_package}}"
    state: latest
  when: ansible_distribution == "Alpine"

- name: generate sshd_config file from template
  template:
    src: "{{ ssh_template_file}}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd